import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import ProviderFunction from "../../redux/provider/provider";
import { Toaster } from "@/components/ui/toaster";
import NavigationEvents from "../../components/navigation";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderFunction>
          <NavigationEvents />
          {children}
        </ProviderFunction>
        <Toaster />
      </body>
    </html>
  );
}
